export const heatmapLayer = {
  type: 'heatmap',
  paint: {
    'heatmap-color': [
      'interpolate',
      ['linear'],
      ['heatmap-density'],
      0,
      'rgba(0, 0, 255, 0)',
      0.1,
      'royalblue',
      0.3,
      'cyan',
      0.5,
      'yellow',
      0.7,
      'orange',
      1,
      'red',
    ],
    'heatmap-opacity': [
      'interpolate',
      ['linear'],
      ['zoom'],
      5.5,
      0.68,
      20,
      0.6,
    ],
    'heatmap-radius': 35,
    'heatmap-weight': [
      'interpolate',
      ['cubic-bezier', 1, 1, 1, 1],
      ['get', 'points'],
      10,
      0.5,
      50,
      0.6,
      100,
      0.7,
      150,
      0.8,
      200,
      0.9,
      250,
      1,
      300,
      1.1,
    ],
    'heatmap-intensity': 0.8,
  },
}
