RootDir                 = "/run/media/alexvish/Data/insta-crawler"
CheckpointUpdateTimeout = "4m"
WorkersNumber           = 20
DataStorageURL          = "10.9.14.118:8082"
UseDataStorage          = false