RootDir = "/home/muskrat/workplace/event-monitoring-system/services/insta-crawler/cmd/data"
DataStorageURL = "localhost:8082"
[[Groups]]
TorPorts = [9151, 9152, 9153, 9154, 9155, 9156, 9157, 9158, 9159, 9160]
Token = "spb_test"
SessionID = "spb_test_id"