Address  = ":17112"
LogPath  = "service.log"
AuthLogPath  = "auth.log"
SessionKey = "kjgnnuig34gsdgjbskg23242sgsk24t2ty2424hghdsbgubt4b34geehgbs"
TimerLogPath  = "timer.log"
ProxyDataPath = "/home/muskrat/workplace/proxy_data_path/"
cors-origin = "http://10.64.0.206:17115/"
User     = "user"
Password = "pwd"
Connector = "storage"
TestMod = true
[conn-params]
address = "localhost:8082"